version: "3.5"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./docker/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./
        target: /usr/share/nginx/html
  php:
    build: ./docker/php
    volumes:
      - type: bind
        source: ./
        target: /usr/share/nginx/html
  data:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
